version: 0.2
# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
    # Use Install phase to install packages or any pre-reqs you may need throughout the build (e.g. dev deps, security checks, etc.)
      - echo "Upgrading SAM CLI to latest version"
      - pip3 install --upgrade aws-sam-cli
      - sam --version
    # Installing project dependencies for integration tests
      - cd integtests
      - npm install
      - cd ..
    # Installing project dependencies for main src
      - cd src
      - npm install
      - cd ..
  pre_build:
    commands:
      # Use Pre-Build phase to run tests, install any code deps or any other customization before build
      - echo "Running unit tests"
      - cd src
      - npm run test
      - cd ..
  build:
    commands:
      # Use Build phase to build your artifacts (compile, package, etc.)
      - echo "Starting SAM build"
      - sam build
  post_build:
    commands:
      # Use Post Build for notifications, git tags and any further customization after build
      - echo "Starting SAM packaging"
      - echo $PACKAGE_BUCKET
      - ls -al
      - sam package --s3-bucket $PACKAGE_BUCKET --output-template-file packaged.yaml

##################################
# Build Artifacts to be uploaded #
##################################

artifacts:
  files:
    # list of local files relative to this build environment that will be added to the final artifact (zip)
    - packaged.yaml
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/continuous-delivery-codepipeline-cfn-artifacts.html
    - template-config.json
  discard-paths: yes

#########################################
# Cache local files for subsequent runs #
#########################################

cache:
  paths:
  # List of path that CodeBuild will upload to S3 Bucket and use in subsequent runs to speed up Builds
  # - '/root/.cache/pip'
