version: 0.2
# Buildspec Reference Doc: https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
    # Use Install phase to install packages or any pre-reqs you may need throughout the build (e.g. dev deps, security checks, etc.)
    #  - echo "Install phase"
    #  - cd api
    #  - npm install
    #  - cd ..
    #  - cd integtests
    #  - npm install
  pre_build:
    commands:
    # Use Pre-Build phase to run tests, install any code deps or any other customization before build
      - echo "Pre-Build phase"
      - echo "Running unit tests"
      - cd api
      - npm run test
      - cd ..
      - echo "Validating SAM template"
      - sam validate
  build:
    commands:
      # Use Build phase to build your artifacts (compile, package, etc.)
      - echo "Starting SAM build"
      - sam build
      # We package the SAM template and create `packaged.yaml` file that will be used in our pipeline for deployment
      ## Here we separate Build from Deployment and segregate permissions for different steps
      - echo "Starting SAM packaging `date` in `pwd`"
      - echo $PACKAGE_BUCKET
      - ls -al
      - sam package --template-file template.yaml --s3-bucket $PACKAGE_BUCKET --output-template-file packaged.yaml
  post_build:
    commands:
      # Use Post Build for notifications, git tags and any further customization after build
      # - echo "[Post-Build phase]"
      - echo "SAM packaging completed on `date`"

##################################
# Build Artifacts to be uploaded #
##################################

artifacts:
  files:
    # list of local files relative to this build environment that will be added to the final artifact (zip)
    - packaged.yaml
  discard-paths: yes

#########################################
# Cache local files for subsequent runs #
#########################################

cache:
  paths:
  # List of path that CodeBuild will upload to S3 Bucket and use in subsequent runs to speed up Builds
  # - '/root/.cache/pip'
