---
swagger: "2.0"
info:
  version: "1.0"
  title: "awsdingler-api"
host: "api.awsdingler.com"
basePath: "/v1"
schemes:
  - "https"
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  cognitoUserPool:
    type: apiKey
    name: "Authorization"
    in: header
    x-amazon-apigateway-authtype: cognito_user_pools
    x-amazon-apigateway-authorizer:
      type: cognito_user_pools
      providerARNs:
        - Fn::Sub: "arn:aws:cognito-idp:us-west-2:${AWS::AccountId}:userpool/us-west-2_IccpkvFLy"
paths:
  /hello:
    get:
      responses: {}
      x-amazon-apigateway-integration:
        uri: 
          Fn::Sub: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/${HelloFunction.Arn}/invocations"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"
  /k8s/hello:
    get:
      responses: {}
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        type: "http_proxy"
        uri: "http://a9a12520b4aa911e980ba02198db823a-ebc7c7512f5f4297.elb.us-west-2.amazonaws.com/"
        passthroughBehavior: "when_no_match"
        responses:
          default:
            statusCode: "200"