AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: awsdingler-serverless-api
Globals:
  Function:
    Timeout: 3

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: app.hello
      Runtime: nodejs8.10
      Layers:
        - !Ref AlgorithmsLayer
      Events:
        Hello:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  ExploreAnnouncements:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      Handler: cron.exploreAnnouncements
      Runtime: nodejs8.10

  AlgorithmsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AwsDinglerAlgorithms
      Description: Reusable algorithmic functions
      ContentUri: layers/nodejs/
      CompatibleRuntimes:
        - nodejs6.10
        - nodejs8.10
      LicenseInfo: 'MIT-0'

Outputs:
  HelloApi:
    Description: "API Gateway endpoint URL for the Hello function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
